- name: "Install epel-release yum"
  ansible.builtin.yum:
    name: epel-release
    update_cache: yes
    state: latest

- name: "Install nginx yum"
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: "replace main nginx config"
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: vagrant
    group: vagrant
    mode: 0644

- name: "Reload nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "reloaded"